"""Tax export for the Accounting module.

Two outputs, both driven off reports.schedule_c() + reports.summary():

  - build_txf()  — a TurboTax **`.txf`** (Tax Exchange Format v042) file. TurboTax
                   Desktop imports it directly (File ▸ Import ▸ From Accounting
                   Software); there is no TurboTax API. Each Schedule C line is
                   emitted as a TXF summary record keyed by its IRS ref code
                   (acct_categories.txf_ref). Lines TXF doesn't carry a ref for
                   (e.g. contract labor, depreciation) are omitted from the file
                   but still appear on the accountant PDF.
  - build_pdf()  — a printable accountant packet (P&L + Schedule C + K-1),
                   rendered HTML→PDF with weasyprint (the house pattern in
                   services/contracts/pdf_renderer.py).

`db` is a tenant-scoped asyncpg connection.
"""
import asyncio
import html as _html

from app.services.accounting import reports, settings_service

TXF_VERSION = "V042"
TXF_SOFTWARE = "AuraFlow Accounting"


def _dollars(cents: int) -> str:
    return f"{cents / 100:.2f}"


def _fmt_money(cents: int) -> str:
    return f"${cents / 100:,.2f}"


async def build_txf(db, year) -> str:
    """Generate the TurboTax .txf for the given tax year."""
    sc = await reports.schedule_c(db, year)
    date_str = f"12/31/{int(year)}" if year else "12/31"

    lines = [TXF_VERSION, f"A{TXF_SOFTWARE}", f"D{date_str}", "^"]
    # Income (Part I) + expenses (Part II) — one summary record per TXF ref code.
    for item in sc["income_lines"] + sc["expense_lines"]:
        ref = item.get("txf_ref")
        if not ref or not item["amount_cents"]:
            continue
        lines += ["TS", f"N{ref}", "C1", "L1", f"${_dollars(item['amount_cents'])}", "^"]
    # TXF is CRLF-terminated per spec.
    return "\r\n".join(lines) + "\r\n"


def _rows_html(items, empty="—") -> str:
    if not items:
        return f'<tr><td colspan="3" class="muted">{empty}</td></tr>'
    out = []
    for it in items:
        out.append(
            f"<tr><td>{_html.escape(it['line'] or '')}</td>"
            f"<td>{_html.escape(it['label'] or '')}</td>"
            f"<td class='num'>{_fmt_money(it['amount_cents'])}</td></tr>"
        )
    return "".join(out)


def _alloc_html(allocs) -> str:
    if not allocs:
        return '<tr><td colspan="5" class="muted">No members on file</td></tr>'
    out = []
    for a in allocs:
        out.append(
            f"<tr><td>{_html.escape(a['name'] or '')}</td>"
            f"<td class='num'>{a['ownership_pct']:.2f}%</td>"
            f"<td class='num'>{_fmt_money(a['share_income_cents'])}</td>"
            f"<td class='num'>{_fmt_money(a['net_allocation_cents'])}</td>"
            f"<td class='num'>{_fmt_money(a['distributions_cents'])}</td></tr>"
        )
    return "".join(out)


async def _build_html(db, year) -> str:
    settings = await settings_service.get_settings(db)
    sc = await reports.schedule_c(db, year)
    ka = await reports.member_allocation(db, year)
    name = _html.escape(settings.get("llc_name") or "Business")
    ein = _html.escape(settings.get("llc_ein") or "")
    yr = int(year) if year else "All years"

    return f"""<!doctype html><html><head><meta charset="utf-8"><style>
      @page {{ size: letter; margin: 0.75in; }}
      body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #1f2937; font-size: 11px; }}
      h1 {{ font-size: 20px; margin: 0 0 2px; }}
      h2 {{ font-size: 13px; margin: 20px 0 6px; border-bottom: 2px solid #059669;
            padding-bottom: 3px; color: #065f46; }}
      .sub {{ color: #6b7280; margin-bottom: 4px; }}
      table {{ width: 100%; border-collapse: collapse; margin-top: 4px; }}
      th, td {{ padding: 4px 6px; text-align: left; }}
      th {{ background: #ecfdf5; font-size: 10px; text-transform: uppercase;
            letter-spacing: .03em; color: #065f46; }}
      tr:nth-child(even) td {{ background: #f9fafb; }}
      .num {{ text-align: right; font-variant-numeric: tabular-nums; }}
      .muted {{ color: #9ca3af; font-style: italic; }}
      .total td {{ font-weight: 700; border-top: 2px solid #d1d5db; background: #fff !important; }}
      .net {{ font-size: 13px; }}
    </style></head><body>
      <h1>{name}</h1>
      <div class="sub">Tax Year {yr}{f' &nbsp;·&nbsp; EIN {ein}' if ein else ''}</div>
      <div class="sub">Schedule C &amp; K-1 packet — generated by AuraFlow Accounting</div>

      <h2>Schedule C — Part I · Income</h2>
      <table><thead><tr><th>Line</th><th>Category</th><th class="num">Amount</th></tr></thead>
        <tbody>{_rows_html(sc['income_lines'], 'No income recorded')}
        <tr class="total"><td></td><td>Gross Receipts</td>
            <td class="num">{_fmt_money(sc['gross_receipts_cents'])}</td></tr></tbody></table>

      <h2>Schedule C — Part II · Expenses</h2>
      <table><thead><tr><th>Line</th><th>Category</th><th class="num">Amount</th></tr></thead>
        <tbody>{_rows_html(sc['expense_lines'], 'No expenses recorded')}
        <tr class="total"><td></td><td>Total Expenses</td>
            <td class="num">{_fmt_money(sc['total_expenses_cents'])}</td></tr>
        <tr class="total net"><td></td><td>Net Profit / (Loss)</td>
            <td class="num">{_fmt_money(sc['net_profit_cents'])}</td></tr></tbody></table>

      <h2>Partner Allocation (Schedule K-1)</h2>
      <table><thead><tr><th>Partner</th><th class="num">Ownership</th>
        <th class="num">Share of Income</th><th class="num">Net Allocation</th>
        <th class="num">Distributions</th></tr></thead>
        <tbody>{_alloc_html(ka['allocations'])}</tbody></table>
    </body></html>"""


async def build_pdf(db, year) -> bytes:
    """Render the accountant packet (P&L + Schedule C + K-1) to PDF bytes."""
    html_str = await _build_html(db, year)
    return await asyncio.to_thread(_render_sync, html_str)


def _render_sync(html_str: str) -> bytes:
    from weasyprint import HTML
    return HTML(string=html_str).write_pdf()
