"""AuraFlow — Square Payment Service

Wraps the official Square Python SDK (squareup==44.0.0+, AsyncSquare).
Used by:
  - The legacy `/payments/square/charge` endpoint that takes a Web
    Payments SDK nonce and charges it on KinovaAI's own Square account
    (preserved for backward compat; do NOT extend it).
  - The Square OAuth flow (square_oauth_service.py) — for studios
    connecting their own merchant accounts.
  - The billing dispatcher (billing_dispatcher.py) — for member-side
    payments / cards / customers / subscriptions / refunds when an
    org's billing_provider='square'. Every method that touches a
    merchant resource accepts the merchant's access_token; methods
    that touch KinovaAI's own resources (platform fee receipt,
    KinovaAI Studio Platform subscription invoices) use the platform
    token from settings.

All operations are idempotent on a caller-supplied idempotency_key
where Square supports it. UUIDs are generated by the service unless
the caller provides one (used by webhook handlers to dedupe).

Error handling: any non-2xx from Square raises ValueError with the
first error.detail. The exception text is safe to surface in API
responses — Square's detail strings are user-friendly (e.g. "Card
declined").
"""
import uuid
from typing import Optional

from square import AsyncSquare
from square.environment import SquareEnvironment

from app.core.config import settings
from app.core.logging import logger


# ── Helpers ──────────────────────────────────────────────────────────────────

def _environment() -> SquareEnvironment:
    """Resolve sandbox vs production env from settings."""
    if (settings.SQUARE_ENVIRONMENT or "sandbox").lower() == "production":
        return SquareEnvironment.PRODUCTION
    return SquareEnvironment.SANDBOX


def _client(access_token: Optional[str] = None) -> AsyncSquare:
    """Return an async Square SDK client. If access_token is None,
    falls back to KinovaAI's own platform token
    (settings.SQUARE_PLATFORM_ACCESS_TOKEN or the legacy
    SQUARE_ACCESS_TOKEN). The platform client is ONLY for KinovaAI's
    own account; per-merchant calls must pass a merchant token
    explicitly.

    NB: squareup 44.x exposes two client classes — `Square` (sync,
    methods like `.create`/`.list`) and `AsyncSquare` (async, same
    method names but awaitable). Methods are NOT suffixed `_async`."""
    token = (
        access_token
        or settings.SQUARE_PLATFORM_ACCESS_TOKEN
        or settings.SQUARE_ACCESS_TOKEN
    )
    if not token:
        raise ValueError("Square is not configured — missing access token")
    return AsyncSquare(token=token, environment=_environment())


def _raise_on_errors(response_errors) -> None:
    """Square SDK responses carry .errors on failure. Raise the first as
    a ValueError so endpoints can return a 400 with a clean message."""
    if not response_errors:
        return
    first = response_errors[0]
    detail = getattr(first, "detail", None) or getattr(first, "code", None) or "Square API error"
    logger.error("Square API error", errors=[
        {"code": getattr(e, "code", None), "detail": getattr(e, "detail", None)}
        for e in response_errors
    ])
    raise ValueError(detail)


def _idem(key: Optional[str] = None) -> str:
    return key or str(uuid.uuid4())


class SquareService:
    """Stateless wrapper around the Square SDK.

    Pass the merchant's OAuth access_token to per-merchant methods.
    Methods without an access_token argument use KinovaAI's platform
    token from settings (used for the legacy charge endpoint AND for
    KinovaAI's own Studio Platform billing in Phase 7).
    """

    # ── Legacy: one-off charge on KinovaAI's platform account ──────────
    # Kept for backward compat with the existing /payments/square/charge
    # endpoint. New code should use create_payment_with_app_fee against
    # a merchant token instead.

    async def create_payment(
        self,
        amount_cents: int,
        source_id: str,
        description: str = "Drop-in class",
        member_id: Optional[str] = None,
    ) -> dict:
        """Charge a Web Payments SDK nonce on KinovaAI's platform account."""
        client = _client()
        body = {
            "idempotency_key": _idem(),
            "source_id": source_id,
            "amount_money": {"amount": amount_cents, "currency": "USD"},
            "location_id": settings.SQUARE_LOCATION_ID or settings.SQUARE_PLATFORM_LOCATION_ID,
            "note": description,
        }
        if member_id:
            body["reference_id"] = member_id
        resp = await client.payments.create(**body)
        _raise_on_errors(getattr(resp, "errors", None))
        payment = resp.payment
        logger.info(
            "Square payment created (legacy)",
            payment_id=payment.id, amount=amount_cents, member_id=member_id,
        )
        return {
            "payment_id": payment.id,
            "status": payment.status,
            "amount_cents": payment.amount_money.amount,
            "receipt_url": getattr(payment, "receipt_url", None),
        }

    async def list_locations(
        self, access_token: Optional[str] = None,
    ) -> list[dict]:
        """List locations on the given merchant account (defaults to
        KinovaAI's platform). Used by OAuth completion to pick a default
        location_id for the studio."""
        client = _client(access_token)
        resp = await client.locations.list()
        _raise_on_errors(getattr(resp, "errors", None))
        return [
            {"id": loc.id, "name": loc.name or "", "status": loc.status or ""}
            for loc in (resp.locations or [])
        ]

    async def get_payment(
        self, payment_id: str, access_token: Optional[str] = None,
    ) -> Optional[dict]:
        client = _client(access_token)
        resp = await client.payments.get(payment_id=payment_id)
        _raise_on_errors(getattr(resp, "errors", None))
        p = resp.payment
        if not p:
            return None
        return {
            "payment_id": p.id,
            "status": p.status,
            "amount_cents": p.amount_money.amount,
            "receipt_url": getattr(p, "receipt_url", None),
        }

    # ── Per-merchant: payments with platform fee ───────────────────────

    async def create_payment_with_app_fee(
        self,
        merchant_access_token: str,
        merchant_location_id: str,
        source_id: str,
        amount_cents: int,
        description: str = "AuraFlow payment",
        member_id: Optional[str] = None,
        customer_id: Optional[str] = None,
        idempotency_key: Optional[str] = None,
        app_fee_cents: Optional[int] = None,
        autocomplete: bool = True,
    ) -> dict:
        """Charge `source_id` on the merchant's Square account, sending
        a 1% application fee to KinovaAI's account.

        source_id may be a one-time payment token from Web Payments SDK
        OR a saved card_id from the Cards API. Square accepts both in
        the same field.
        """
        if app_fee_cents is None:
            from app.services.payments.billing_dispatcher import _square_app_fee
            app_fee_cents = _square_app_fee(amount_cents)

        client = _client(merchant_access_token)
        body: dict = {
            "idempotency_key": _idem(idempotency_key),
            "source_id": source_id,
            "amount_money": {"amount": amount_cents, "currency": "USD"},
            "location_id": merchant_location_id,
            "autocomplete": autocomplete,
            "app_fee_money": {"amount": app_fee_cents, "currency": "USD"},
            "note": description[:500] if description else None,
        }
        if member_id:
            body["reference_id"] = member_id[:40]
        if customer_id:
            body["customer_id"] = customer_id
        body = {k: v for k, v in body.items() if v is not None}

        resp = await client.payments.create(**body)
        _raise_on_errors(getattr(resp, "errors", None))
        p = resp.payment
        logger.info(
            "Square payment created",
            payment_id=p.id, amount=amount_cents, app_fee=app_fee_cents,
            member_id=member_id,
        )
        return {
            "payment_id": p.id,
            "status": p.status,
            "amount_cents": p.amount_money.amount,
            "app_fee_cents": app_fee_cents,
            "receipt_url": getattr(p, "receipt_url", None),
            "card_brand": getattr(getattr(p, "card_details", None), "card", None)
                          and getattr(p.card_details.card, "card_brand", None),
        }

    async def refund_payment(
        self,
        merchant_access_token: str,
        payment_id: str,
        amount_cents: int,
        reason: Optional[str] = None,
        idempotency_key: Optional[str] = None,
    ) -> dict:
        client = _client(merchant_access_token)
        body = {
            "idempotency_key": _idem(idempotency_key),
            "payment_id": payment_id,
            "amount_money": {"amount": amount_cents, "currency": "USD"},
        }
        if reason:
            body["reason"] = reason[:192]
        resp = await client.refunds.refund_payment(**body)
        _raise_on_errors(getattr(resp, "errors", None))
        r = resp.refund
        logger.info(
            "Square refund created", refund_id=r.id, payment_id=payment_id,
            amount=amount_cents,
        )
        return {
            "refund_id": r.id,
            "payment_id": payment_id,
            "amount_cents": r.amount_money.amount,
            "status": r.status,
        }

    # ── Customers + Cards (save-on-file) ───────────────────────────────

    async def create_customer(
        self,
        merchant_access_token: str,
        email: str,
        first_name: Optional[str] = None,
        last_name: Optional[str] = None,
        phone: Optional[str] = None,
        member_id: Optional[str] = None,
    ) -> dict:
        """Create a Square Customer under the merchant. `member_id` is
        stored in reference_id for cross-system lookup."""
        client = _client(merchant_access_token)
        body: dict = {
            "idempotency_key": _idem(),
            "email_address": email,
        }
        if first_name:
            body["given_name"] = first_name
        if last_name:
            body["family_name"] = last_name
        if phone:
            body["phone_number"] = phone
        if member_id:
            body["reference_id"] = member_id[:100]
        resp = await client.customers.create(**body)
        _raise_on_errors(getattr(resp, "errors", None))
        c = resp.customer
        return {
            "customer_id": c.id,
            "email": c.email_address,
            "reference_id": getattr(c, "reference_id", None),
        }

    async def create_card(
        self,
        merchant_access_token: str,
        customer_id: str,
        source_id: str,
        cardholder_name: Optional[str] = None,
        idempotency_key: Optional[str] = None,
    ) -> dict:
        """Save a card on file from a Web Payments SDK nonce.

        Per Don's standing rule (feedback_always_save_card.md): ALWAYS
        save the card. Every first member payment runs through this
        before / after create_payment_with_app_fee to ensure the card
        survives for future charges.
        """
        client = _client(merchant_access_token)
        body: dict = {
            "idempotency_key": _idem(idempotency_key),
            "source_id": source_id,
            "card": {
                "customer_id": customer_id,
            },
        }
        if cardholder_name:
            body["card"]["cardholder_name"] = cardholder_name[:100]
        resp = await client.cards.create(**body)
        _raise_on_errors(getattr(resp, "errors", None))
        card = resp.card
        return {
            "card_id": card.id,
            "customer_id": customer_id,
            "card_brand": getattr(card, "card_brand", None),
            "last_4": getattr(card, "last_4", None),
            "exp_month": getattr(card, "exp_month", None),
            "exp_year": getattr(card, "exp_year", None),
        }

    async def disable_card(
        self,
        merchant_access_token: str,
        card_id: str,
    ) -> dict:
        client = _client(merchant_access_token)
        resp = await client.cards.disable(card_id=card_id)
        _raise_on_errors(getattr(resp, "errors", None))
        return {"card_id": card_id, "disabled": True}

    # ── Subscriptions (per-merchant member memberships in Phase 6) ─────

    async def create_subscription_plan(
        self,
        merchant_access_token: str,
        name: str,
        price_cents: int,
        cadence: str = "MONTHLY",
    ) -> dict:
        """Create a Subscription Plan + a default Plan Variation. Square
        models a Plan as a Catalog object; the Variation carries the
        price + cadence. cadence ∈ {DAILY, WEEKLY, EVERY_TWO_WEEKS,
        THIRTY_DAYS, SIXTY_DAYS, NINETY_DAYS, MONTHLY, EVERY_TWO_MONTHS,
        QUARTERLY, EVERY_FOUR_MONTHS, EVERY_SIX_MONTHS, ANNUAL,
        EVERY_TWO_YEARS}.
        """
        client = _client(merchant_access_token)
        plan_id = f"#auraflow-plan-{uuid.uuid4().hex[:12]}"
        variation_id = f"#auraflow-var-{uuid.uuid4().hex[:12]}"
        resp = await client.catalog.batch_upsert(
            idempotency_key=_idem(),
            batches=[{
                "objects": [
                    {
                        "type": "SUBSCRIPTION_PLAN",
                        "id": plan_id,
                        "subscription_plan_data": {
                            "name": name[:255],
                            "subscription_plan_variations": [
                                {
                                    "type": "SUBSCRIPTION_PLAN_VARIATION",
                                    "id": variation_id,
                                    "subscription_plan_variation_data": {
                                        "name": name[:255],
                                        "phases": [{
                                            "cadence": cadence,
                                            "pricing": {
                                                "type": "STATIC",
                                                "price_money": {
                                                    "amount": price_cents,
                                                    "currency": "USD",
                                                },
                                            },
                                        }],
                                    },
                                },
                            ],
                        },
                    },
                ],
            }],
        )
        _raise_on_errors(getattr(resp, "errors", None))
        # The response remaps the placeholder IDs (the `#` prefix) to
        # real Square Catalog IDs via id_mappings.
        mappings = {m.client_object_id: m.object_id for m in (resp.id_mappings or [])}
        return {
            "plan_id": mappings.get(plan_id, plan_id),
            "plan_variation_id": mappings.get(variation_id, variation_id),
        }

    async def create_subscription(
        self,
        merchant_access_token: str,
        merchant_location_id: str,
        plan_variation_id: str,
        customer_id: str,
        card_id: str,
        start_date: Optional[str] = None,  # YYYY-MM-DD; default = today
        reference_id: Optional[str] = None,
    ) -> dict:
        client = _client(merchant_access_token)
        body: dict = {
            "idempotency_key": _idem(),
            "location_id": merchant_location_id,
            "plan_variation_id": plan_variation_id,
            "customer_id": customer_id,
            "card_id": card_id,
        }
        if start_date:
            body["start_date"] = start_date
        if reference_id:
            body["source"] = {"name": reference_id[:32]}
        resp = await client.subscriptions.create(**body)
        _raise_on_errors(getattr(resp, "errors", None))
        sub = resp.subscription
        return {
            "subscription_id": sub.id,
            "status": sub.status,
            "start_date": getattr(sub, "start_date", None),
        }

    async def pause_subscription(
        self,
        merchant_access_token: str,
        subscription_id: str,
    ) -> dict:
        """Pause a Square subscription IMMEDIATELY (not at period end).
        Don's standing rule (feedback_timezone): all dates are Pacific.
        Using UTC "today" would schedule the pause for tomorrow Pacific
        when staff click freeze after 5pm PT — clearly wrong.
        """
        from datetime import datetime
        from zoneinfo import ZoneInfo
        today_pt = datetime.now(ZoneInfo("America/Los_Angeles")).strftime("%Y-%m-%d")
        client = _client(merchant_access_token)
        resp = await client.subscriptions.pause(
            subscription_id=subscription_id,
            pause_effective_date=today_pt,
        )
        _raise_on_errors(getattr(resp, "errors", None))
        return {"subscription_id": subscription_id, "status": "PAUSED"}

    async def resume_subscription(
        self,
        merchant_access_token: str,
        subscription_id: str,
    ) -> dict:
        """Resume a paused Square subscription IMMEDIATELY. Square
        requires resume_effective_date AFTER the scheduled pause date.
        Tomorrow Pacific is the earliest accepted value for a same-day
        Pacific pause."""
        from datetime import datetime, timedelta
        from zoneinfo import ZoneInfo
        tomorrow_pt = (
            datetime.now(ZoneInfo("America/Los_Angeles")) + timedelta(days=1)
        ).strftime("%Y-%m-%d")
        client = _client(merchant_access_token)
        resp = await client.subscriptions.resume(
            subscription_id=subscription_id,
            resume_effective_date=tomorrow_pt,
            resume_change_timing="IMMEDIATE",
        )
        _raise_on_errors(getattr(resp, "errors", None))
        return {"subscription_id": subscription_id, "status": "ACTIVE"}

    async def cancel_subscription(
        self,
        merchant_access_token: str,
        subscription_id: str,
    ) -> dict:
        """Schedule the subscription to cancel at the end of the current
        billing period. Square doesn't support immediate cancellation
        for active subs — they continue until period end."""
        client = _client(merchant_access_token)
        resp = await client.subscriptions.cancel(subscription_id=subscription_id)
        _raise_on_errors(getattr(resp, "errors", None))
        return {"subscription_id": subscription_id, "status": "CANCELED"}

    async def get_subscription(
        self,
        merchant_access_token: str,
        subscription_id: str,
    ) -> Optional[dict]:
        client = _client(merchant_access_token)
        resp = await client.subscriptions.get(subscription_id=subscription_id)
        _raise_on_errors(getattr(resp, "errors", None))
        s = resp.subscription
        if not s:
            return None
        return {
            "subscription_id": s.id,
            "status": s.status,
            "card_id": getattr(s, "card_id", None),
            "start_date": getattr(s, "start_date", None),
            "charged_through_date": getattr(s, "charged_through_date", None),
        }

    # ── Invoices (KinovaAI → studio platform billing in Phase 8) ───────

    async def create_invoice(
        self,
        access_token: str,
        location_id: str,
        customer_id: str,
        order_lines: list[dict],
        title: str,
        description: Optional[str] = None,
        scheduled_at: Optional[str] = None,
        card_id_on_file: Optional[str] = None,
        delivery_method: str = "EMAIL",
    ) -> dict:
        """Create an Order + Invoice on the given Square account.

        Used in two places:
          - KinovaAI's account → studio: monthly platform invoice with
            plan fee + AI token overage lines.
          - A merchant's account → member: one-off bills (future use).

        order_lines: [{"name": str, "amount_cents": int, "quantity": int=1}, ...]
        """
        client = _client(access_token)

        # 1. Create the Order
        line_items = [
            {
                "name": ln["name"][:255],
                "quantity": str(ln.get("quantity", 1)),
                "base_price_money": {
                    "amount": ln["amount_cents"],
                    "currency": "USD",
                },
            }
            for ln in order_lines
        ]
        order_resp = await client.orders.create(
            idempotency_key=_idem(),
            order={
                "location_id": location_id,
                "customer_id": customer_id,
                "line_items": line_items,
                "state": "DRAFT",
            },
        )
        _raise_on_errors(getattr(order_resp, "errors", None))
        order_id = order_resp.order.id

        # 2. Create the Invoice attached to the Order
        invoice_body: dict = {
            "idempotency_key": _idem(),
            "invoice": {
                "location_id": location_id,
                "order_id": order_id,
                "primary_recipient": {"customer_id": customer_id},
                "title": title[:255],
                "delivery_method": delivery_method,
                "accepted_payment_methods": {"card": True},
                "payment_requests": [
                    {
                        "request_type": "BALANCE",
                        "due_date": scheduled_at,  # auto-charge on this date
                        "automatic_payment_source": "CARD_ON_FILE" if card_id_on_file else "NONE",
                        "card_id": card_id_on_file,
                    }
                ],
            },
        }
        if description:
            invoice_body["invoice"]["description"] = description[:65535]
        if scheduled_at:
            invoice_body["invoice"]["scheduled_at"] = scheduled_at

        # Filter None values out of payment_request
        invoice_body["invoice"]["payment_requests"][0] = {
            k: v for k, v in invoice_body["invoice"]["payment_requests"][0].items()
            if v is not None
        }

        invoice_resp = await client.invoices.create(**invoice_body)
        _raise_on_errors(getattr(invoice_resp, "errors", None))
        inv = invoice_resp.invoice

        # 3. Publish (transitions DRAFT → SCHEDULED/UNPAID). Square
        # requires a separate publish call; without it the invoice
        # never charges.
        publish_resp = await client.invoices.publish(
            invoice_id=inv.id,
            version=inv.version or 0,
            idempotency_key=_idem(),
        )
        _raise_on_errors(getattr(publish_resp, "errors", None))
        published = publish_resp.invoice

        logger.info(
            "Square invoice created + published",
            invoice_id=published.id, order_id=order_id, customer_id=customer_id,
            total_cents=sum(ln["amount_cents"] for ln in order_lines),
        )
        return {
            "invoice_id": published.id,
            "order_id": order_id,
            "status": published.status,
            "public_url": getattr(published, "public_url", None),
        }


square_service = SquareService()
